// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eval_continuous_density_cpp
arma::vec eval_continuous_density_cpp(const arma::mat& Y, const arma::vec& mu, const arma::mat& Sigma);
RcppExport SEXP _mixLCA_eval_continuous_density_cpp(SEXP YSEXP, SEXP muSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_continuous_density_cpp(Y, mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// eval_spectral_density_cpp
arma::vec eval_spectral_density_cpp(const arma::mat& Z, const arma::umat& Z_mis, const arma::vec& pi_c_raw, const arma::mat& A_star, const arma::ivec& item_starts, const arma::ivec& item_sizes);
RcppExport SEXP _mixLCA_eval_spectral_density_cpp(SEXP ZSEXP, SEXP Z_misSEXP, SEXP pi_c_rawSEXP, SEXP A_starSEXP, SEXP item_startsSEXP, SEXP item_sizesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type Z_mis(Z_misSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pi_c_raw(pi_c_rawSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A_star(A_starSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type item_starts(item_startsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type item_sizes(item_sizesSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_spectral_density_cpp(Z, Z_mis, pi_c_raw, A_star, item_starts, item_sizes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mixLCA_eval_continuous_density_cpp", (DL_FUNC) &_mixLCA_eval_continuous_density_cpp, 3},
    {"_mixLCA_eval_spectral_density_cpp", (DL_FUNC) &_mixLCA_eval_spectral_density_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mixLCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
