# ==============================================================================
# File: R/data.R
# mixLCA - documentation for embedded example datasets.
# ==============================================================================

#' Synthetic Voter Perceptions of Two Hypothetical Candidates
#'
#' A simulated dataset of 2000 respondents rating two hypothetical political
#' candidates ("A" and "B") on six attributes: moral character (\code{moral}),
#' competence (\code{compet}), leadership (\code{lead}), honesty
#' (\code{honest}), intelligence (\code{intel}), and empathy (\code{empath}).
#' Each attribute appears twice, once for each candidate, distinguished by
#' the suffix \code{_A} or \code{_B}.
#'
#' Ratings are ordered four-level factors (\code{poor}, \code{fair},
#' \code{good}, \code{excellent}). The generative model is a three-class
#' mixture: a strong A-favoring class (40\%), a strong B-favoring class
#' (40\%), and a moderate / ambivalent class (20\%). Within each class, a
#' shared latent factor induces local dependence between the six items
#' rating the same candidate; this makes the dataset useful for
#' demonstrating bivariate residual diagnostics (\code{\link{bvr_categorical}})
#' and spectral local dependence (\code{\link{auto_sld}}).
#'
#' The data are synthetic, authored by the package author for didactic
#' purposes, and are licensed under GPL (>= 3) along with the rest of the
#' package. A reproducible generation script is provided in the source
#' tree at \code{data-raw/make-example-data.R}.
#'
#' The substantive analog (not the source) is the rating-scale design used
#' in the American National Election Studies (ANES), where respondents
#' rate presidential candidates on attribute dimensions. For published
#' analyses of real ANES data, see for example Bartle (2000) or related
#' political-cognition literature.
#'
#' @format A data frame with 2000 rows and 12 columns. All columns are
#'   ordered factors with levels \code{poor < fair < good < excellent}.
#' \describe{
#'   \item{moral_A, moral_B}{Rating of moral character for candidates A and B.}
#'   \item{compet_A, compet_B}{Rating of competence.}
#'   \item{lead_A, lead_B}{Rating of leadership.}
#'   \item{honest_A, honest_B}{Rating of honesty.}
#'   \item{intel_A, intel_B}{Rating of intelligence.}
#'   \item{empath_A, empath_B}{Rating of empathy.}
#' }
#'
#' @source Synthetic data, generated by
#'   \code{data-raw/make-example-data.R}.
#'
#' @references Bartle, J. (2000). Political awareness, opinion
#'   constraint and the stability of ideological positions.
#'   \emph{Political Studies}, 48(3), 467-484.
#'
#' @examples
#' data(voter_perceptions)
#' head(voter_perceptions)
#' table(voter_perceptions$moral_A, voter_perceptions$moral_B)
"voter_perceptions"


#' Synthetic Health-Screening Dataset with Distal Outcome
#'
#' A simulated dataset of 800 subjects undergoing a health screening
#' protocol. Four continuous biomarkers form a two-class latent structure;
#' an antecedent age covariate shifts class membership; a binary screening
#' outcome (\code{yes} / \code{no}) follows the latent class with a mild
#' additional age effect.
#'
#' This dataset is designed to demonstrate the partitioned architecture
#' supported by \code{\link{fit_lca}}: concomitant predictors (here
#' \code{age}) enter the measurement model through multinomial logistic
#' regression on class membership, while the distal outcome
#' (\code{outcome}) is estimated separately via
#' \code{\link{distal}} under Bolck-Croon-Hagenaars (BCH) inverse-
#' classification-error weighting.
#'
#' The data are synthetic, authored by the package author for didactic
#' purposes, and are licensed under GPL (>= 3) along with the rest of
#' the package. A reproducible generation script is provided in the
#' source tree at \code{data-raw/make-example-data.R}.
#'
#' We deliberately do not derive this dataset from any real screening
#' cohort. Labeling participants by latent "metabolic class" can carry
#' substantive implications that we leave to domain researchers; the
#' synthetic construction here avoids importing those framings while
#' preserving the joint structure (mixed continuous indicators,
#' antecedent covariate, distal outcome) that the package is designed
#' to model.
#'
#' @format A data frame with 800 rows and 6 columns.
#' \describe{
#'   \item{marker_1}{Numeric. Loosely log-normal continuous indicator
#'     (class-1 median around 80, class-2 around 140).}
#'   \item{marker_2}{Numeric. Loosely log-normal continuous indicator
#'     (class-1 median around 70, class-2 around 95).}
#'   \item{marker_3}{Numeric. Loosely log-normal continuous indicator
#'     (class-1 median around 22, class-2 around 33).}
#'   \item{marker_4}{Numeric. Loosely log-normal continuous indicator
#'     (class-1 median around 0.30, class-2 around 0.60).}
#'   \item{age}{Numeric. Age in years (truncated to 25-70).}
#'   \item{outcome}{Factor with levels \code{no} and \code{yes}: the
#'     binary distal outcome.}
#' }
#'
#' @source Synthetic data, generated by
#'   \code{data-raw/make-example-data.R}.
#'
#' @references For methodological background on the partitioned LCA
#'   architecture used here, see Vermunt (2010), \emph{Latent class
#'   modeling with covariates: two improved three-step approaches},
#'   Political Analysis, 18(4), 450-469.
#'
#' @examples
#' data(health_screening)
#' summary(health_screening)
#' with(health_screening, table(outcome, age_bin = cut(age, c(20, 40, 55, 75))))
"health_screening"
