# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eval_continuous_density_cpp <- function(Y, mu, Sigma) {
    .Call(`_mixLCA_eval_continuous_density_cpp`, Y, mu, Sigma)
}

eval_spectral_density_cpp <- function(Z, Z_mis, pi_c_raw, A_star, item_starts, item_sizes) {
    .Call(`_mixLCA_eval_spectral_density_cpp`, Z, Z_mis, pi_c_raw, A_star, item_starts, item_sizes)
}

